import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <header>
          <nav>
            <div className="contato">
              <a href="contato.html">
                <i className="fas fa-envelope"></i>
                <p className="fale-conosco">Fale conosco!</p>
              </a>
              <div id="cont-linha"></div>
            </div>
            <ul className="main_menu">
              <li>
                <a className="menu" href="/">
                  HOME
                </a>
              </li>
              <li>
                <a
                  className="menu"
                  href="https://api.whatsapp.com"
                  target="_blank"
                >
                  <i className="fab fa-whatsapp"></i>
                </a>
              </li>
              <li>
                <a
                  className="menu"
                  href="https://www.instagram.com"
                  target="_blank"
                >
                  <i className="fab fa-instagram"></i>
                </a>
              </li>
            </ul>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
